name: StockAnalyzer
options:
  bundleIdPrefix: com.stockanalyzer
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"

targets:
  StockAnalyzer:
    type: application
    platform: iOS
    sources:
      - StockAnalyzer
    settings:
      base:
        INFOPLIST_FILE: StockAnalyzer/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.stockanalyzer.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR: "NO"
